import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import PrelineScript from "../components/PrelineScript";
import NavBar from "../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={inter.className}>
        <header className="flex flex-wrap sm:justify-start sm:flex-nowrap z-50 w-full text-sm">
          <NavBar />
        </header>

        <main id="content" role="main">
          {children}
        </main>
      </body>
      <PrelineScript />
    </html>
  );
}
